/* ============================================================
   Robot Fragrances — build stamp
   ------------------------------------------------------------
   Writes worker/src/version.js so a running worker can say which
   commit it is. Wrangler runs this automatically before bundling
   (see [build] in wrangler.toml), so there is nothing to remember.

   This exists because of a real outage: a bad build replaced the
   checkout API with the storefront, and /api/health could say the
   worker was broken but not WHICH build was live. Diagnosing took
   far longer than it should have.

   Workers Builds injects the commit SHA into the build environment;
   locally we fall back to asking git.
   ============================================================ */
"use strict";

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const OUT = path.join(__dirname, "..", "worker/src/version.js");

function commitSha() {
  /* Workers Builds sets these; names differ across CI providers, so
     take whichever is present before falling back to git. */
  const fromEnv =
    process.env.WORKERS_CI_COMMIT_SHA ||
    process.env.CF_PAGES_COMMIT_SHA ||
    process.env.GITHUB_SHA ||
    process.env.COMMIT_SHA;
  if (fromEnv) return fromEnv;

  try {
    return execSync("git rev-parse HEAD", { stdio: ["ignore", "pipe", "ignore"] })
      .toString().trim();
  } catch (e) {
    return "unknown";
  }
}

function branch() {
  const fromEnv = process.env.WORKERS_CI_BRANCH || process.env.GITHUB_REF_NAME;
  if (fromEnv) return fromEnv;
  try {
    return execSync("git rev-parse --abbrev-ref HEAD", { stdio: ["ignore", "pipe", "ignore"] })
      .toString().trim();
  } catch (e) {
    return "unknown";
  }
}

const sha = commitSha();
const body =
  "/* GENERATED by scripts/stamp-version.js — do not edit. */\n" +
  `export const VERSION = ${JSON.stringify(sha.slice(0, 12))};\n` +
  `export const BRANCH = ${JSON.stringify(branch())};\n` +
  `export const BUILT_AT = ${JSON.stringify(new Date().toISOString())};\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.log(`version stamp → ${sha.slice(0, 12)} (${branch()})`);
